// Central theme system — light and dark mode color tokens
export const lightTheme = {
    isDark: false,
    bg: '#F5F7FF',
    bgSecondary: '#ECEEF8',
    surface: '#FFFFFF',
    surface2: '#F0F2FF',
    border: '#E2E5F0',
    primary: '#6C63FF',
    primaryDark: '#4F46E5',
    primaryLight: '#EEF0FF',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    success: '#10B981',
    successBg: '#ECFDF5',
    danger: '#EF4444',
    dangerBg: '#FEF2F2',
    warning: '#F59E0B',
    warningBg: '#FFFBEB',
    shadow: {
        shadowColor: '#6C63FF',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    shadowStrong: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
};

export const darkTheme = {
    isDark: true,
    bg: '#0F0F1A',
    bgSecondary: '#131324',
    surface: '#1C1C2E',
    surface2: '#252538',
    border: '#2E2E45',
    primary: '#6C63FF',
    primaryDark: '#4F46E5',
    primaryLight: '#1E1B4B',
    text: '#FFFFFF',
    textSecondary: '#A0A0C0',
    textMuted: '#6B6B8A',
    success: '#10B981',
    successBg: '#052E16',
    danger: '#EF4444',
    dangerBg: '#2D0A0A',
    warning: '#F59E0B',
    warningBg: '#2D1F00',
    shadow: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    shadowStrong: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 6,
    },
};

export type Theme = typeof lightTheme;
